### ISSUE TITLE
9 - 11 Serverside

### ISSUE THREAD

**Issue by Dosant** [sikmakn/exadel#9]
@sikmakn, Привет. 
Попробовал запустить. 
После логина получаю ошибку на GET FirstNews

`TypeError: Cannot read property 'findOne' of undefined
    at MyStore.destroy (/Users/antondosov/Downloads/exadel-master/newsSiteWithExpress/private/myStoreSession.js:90:28)
    at MyStore.get (/Users/antondosov/Downloads/exadel-master/newsSiteWithExpress/private/myStoreSession.js:66:10)
    at session (/Users/antondosov/Downloads/exadel-master/newsSiteWithExpress/node_modules/express-session/index.js:460:11)
    at Layer.handle [as handle_request] (/Users/antondosov/Downloads/exadel-master/newsSiteWithExpress/node_modules/express/lib/router/layer.js:95:5)
`

Сделай монго, потести нормально и приходи в во вторник, покажешь.  - Будет 2 пары практики для выставления оценок и зачетов. По-моему в 9:35 в 517

**Comment by sikmakn** [comment]
Да, только заметил, более ранний вариант сохраненный со встроенным store работает. Свой так и не получилось нормально сделать. Я по семейным обстоятельствам уезжал на две недели, не было возможности  делать. Можно просто скинуть сюда последнее задание, у меня во вторник экзамен на военной кафедре?

**Comment by Dosant** [comment]
Понял.
Ок, сделай здесь полностью рабочий вариант с 12-ым заданием, чем раньше до вторника, тем лучше. 

Напиши, как сделаешь

**Comment by sikmakn** [comment]
Сделал 12ое, не разобрался какой именно файл нужно скидывать. Сделал за ночь, из-за поездки полный аврал, вроде все проверил - работает, но времени сделать код более красивым не было. Я весь семестр старался делать на максимальную оценку, и вовремя, надеюсь есть шанс попасть на практику?

**Comment by Dosant** [comment]
Какой уровень английского? intermediate? upper? advanced?

**Comment by Dosant** [comment]
Под экспортом понималась база данных в json файлы: 
https://docs.mongodb.com/manual/reference/program/mongoexport/

Еще добавь в .gitignore папку db

**Comment by Dosant** [comment]
Если будет время, задеплой лучше базу данных удаленно,
например, https://www.mongolab.com

Тогда нам будет проще посмотреть на результат: с удаленной базой данных.

**Comment by sikmakn** [comment]
Добавил .json коллекции. Уровень где-то pre-intermediate, но я сейчас им не занимаюсь специализированно, летом думаю заняться серьезно, смотрю какие курсы есть. У меня быстро забывается и вспоминается язык, поэтому уровень может быстро подскочить когда занимаюсь им, потому что много где учил и оно откладывается в подкорке.

**Comment by Dosant** [comment]
👍

**Comment by sikmakn** [comment]
Я правильно добавил .json? пока заполнил парой записей, могу набить побольше, если верно понял

**Comment by Dosant** [comment]
Да, все верно. Больше не надо :)

**Comment by sikmakn** [comment]
Отлично)

**Comment by sikmakn** [comment]
Можно узнать свою оценку и есть ли шансы в exadel попасть?

**Comment by Dosant** [comment]
Привет, 10. Да, мы рекомендовали тебя.
Жанна Витальевна обещает в течение недели связаться с людьми, которых пригласят.

**Comment by sikmakn** [comment]
Отлично, спасибо большое)
